// The 3D Print Log monitoring workbook. See README.md for how to deploy and edit it.
//
// The workbook definition lives in workbook.json (generated by build_workbook.py) and is
// environment-neutral: the two App Insights resource ids are substituted here, so the same
// file deploys to the dev resource group unchanged.

targetScope = 'resourceGroup'

@description('Resource id of the API Application Insights component.')
param apiInsightsId string

@description('Resource id of the UI Application Insights component.')
param uiInsightsId string

@description('Name shown in the Workbooks gallery.')
param displayName string = '3D Print Log'

param location string = resourceGroup().location

var serializedData = replace(
  replace(loadTextContent('workbook.json'), '__API_RESOURCE_ID__', apiInsightsId),
  '__UI_RESOURCE_ID__',
  uiInsightsId
)

// A workbook's name is a GUID. Deriving it from the resource group keeps every deploy an
// in-place update of the same resource rather than a second copy in the gallery.
resource workbook 'Microsoft.Insights/workbooks@2022-04-01' = {
  name: guid(resourceGroup().id, 'printlog-monitoring')
  location: location
  kind: 'shared'
  properties: {
    displayName: displayName
    category: 'workbook'
    // The workbook appears in this resource's Workbooks gallery, and this is the
    // resource its queries run against when a parameter has no value.
    sourceId: apiInsightsId
    serializedData: serializedData
    version: 'Notebook/1.0'
  }
}

output workbookId string = workbook.id
output portalUrl string = 'https://portal.azure.com/#resource${workbook.id}/workbook'
