// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrintLogApi;

namespace PrintLogApi.Migrations
{
    [DbContext(typeof(PrintLogContext))]
    [Migration("20190923181619_AddTimestampToPrint")]
    partial class AddTimestampToPrint
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PrintLogApi.Models.Print", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedById");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("EstimatedFilamentUsageMg");

                    b.Property<int?>("EstimatedPrintTimeInSeconds");

                    b.Property<string>("FilamentType");

                    b.Property<int?>("FilamentUsageMg");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000);

                    b.Property<int?>("PrintTimeInSeconds");

                    b.Property<long>("PrinterId");

                    b.Property<int>("Status");

                    b.Property<long>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("Url")
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PrinterId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Prints");
                });

            modelBuilder.Entity("PrintLogApi.Models.Printer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<double>("FilamentDiameter");

                    b.Property<string>("Make")
                        .HasMaxLength(50);

                    b.Property<string>("Model")
                        .HasMaxLength(50);

                    b.Property<double>("NozzleDiameter");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("PrintLogApi.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("OAuthUserId");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PrintLogApi.Models.Print", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrintLogApi.Models.Printer", "printer")
                        .WithMany()
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PrintLogApi.Models.Printer", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "User")
                        .WithMany("printers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
