// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrintLogApi;

namespace PrintLogApi.Migrations
{
    [DbContext(typeof(PrintLogContext))]
    [Migration("20200607233247_AddUserSettingTypes")]
    partial class AddUserSettingTypes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PrintLogApi.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CreatedById");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email")
                        .HasMaxLength(1000);

                    b.Property<string>("Note")
                        .HasMaxLength(5000);

                    b.Property<int>("Type");

                    b.Property<long>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("PrintLogApi.Models.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CreatedById");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Path");

                    b.Property<long>("Size");

                    b.Property<long>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("PrintLogApi.Models.Print", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedById");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int?>("EstimatedFilamentUsageMg");

                    b.Property<int?>("EstimatedPrintTimeInSeconds");

                    b.Property<string>("FilamentType")
                        .HasMaxLength(100);

                    b.Property<int?>("FilamentUsageMg");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000);

                    b.Property<int?>("PrintTimeInSeconds");

                    b.Property<long>("PrinterId");

                    b.Property<DateTimeOffset?>("StartDate");

                    b.Property<int>("Status");

                    b.Property<string>("Title")
                        .HasMaxLength(100);

                    b.Property<long>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<string>("Url")
                        .HasMaxLength(1000);

                    b.Property<int>("ViewStatus");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PrinterId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Prints");
                });

            modelBuilder.Entity("PrintLogApi.Models.PrintImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedById");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<Guid>("FileId");

                    b.Property<bool>("IsDefault");

                    b.Property<long>("PrintId");

                    b.Property<long>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FileId");

                    b.HasIndex("PrintId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("PrintImages");
                });

            modelBuilder.Entity("PrintLogApi.Models.Printer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<double>("FilamentDiameter");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Make")
                        .HasMaxLength(50);

                    b.Property<string>("Model")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.Property<double>("NozzleDiameter");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("PrintLogApi.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bio")
                        .HasMaxLength(1000);

                    b.Property<string>("CoverPicture");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(30);

                    b.Property<string>("OAuthUserId");

                    b.Property<string>("ProfilePicture");

                    b.Property<int>("ViewStatus");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PrintLogApi.Models.UserSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CreatedById");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<long>("UpdatedById");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<long?>("UserId");

                    b.Property<int>("UserSettingTypeId");

                    b.Property<string>("Value")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSettingTypeId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("PrintLogApi.Models.UserSettingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("UserSettingTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Default View Status for a print.",
                            Name = "Prints_DefaultPrintViewStatus"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The Id of the printer that was last selected.",
                            Name = "Prints_LastSelectedPrinterId"
                        });
                });

            modelBuilder.Entity("PrintLogApi.Models.Feedback", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PrintLogApi.Models.File", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PrintLogApi.Models.Print", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrintLogApi.Models.Printer", "Printer")
                        .WithMany()
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PrintLogApi.Models.PrintImage", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrintLogApi.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrintLogApi.Models.Print", "Print")
                        .WithMany("Images")
                        .HasForeignKey("PrintId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PrintLogApi.Models.Printer", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "User")
                        .WithMany("printers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PrintLogApi.Models.UserSetting", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PrintLogApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("PrintLogApi.Models.UserSettingType", "UserSettingType")
                        .WithMany()
                        .HasForeignKey("UserSettingTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
