// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrintLogApi;

#nullable disable

namespace PrintLogApi.Migrations
{
    [DbContext(typeof(PrintLogContext))]
    [Migration("20260716100815_AddMcpRequestFingerprint")]
    partial class AddMcpRequestFingerprint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrintLogApi.Models.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("PrintLogApi.Models.CuraSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CuraVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PluginVersion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("_Settings")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Settings");

                    b.HasKey("Id");

                    b.ToTable("CuraSettings");
                });

            modelBuilder.Entity("PrintLogApi.Models.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Note")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ResolvedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ResolvedNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("PrintLogApi.Models.Filament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("ColorName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ColorPattern")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Colors")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DiameterMm")
                        .HasColumnType("float");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.PrimitiveCollection<string>("Effects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FinishType")
                        .HasColumnType("int");

                    b.Property<string>("InertGas")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("InitialLayerTimeS")
                        .HasColumnType("float");

                    b.Property<double?>("InitialNominalLengthM")
                        .HasColumnType("float");

                    b.Property<double?>("InitialNominalVolumeMl")
                        .HasColumnType("float");

                    b.Property<long?>("InitialNominalWeightMg")
                        .HasColumnType("bigint");

                    b.Property<long?>("InitialTotalWeightMg")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<double?>("LayerTimeS")
                        .HasColumnType("float");

                    b.Property<string>("MaterialCategoryNickname")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("filament");

                    b.Property<double>("MaterialDensityGramPerCubicCm")
                        .HasColumnType("float");

                    b.Property<double?>("MaterialRefreshRatio")
                        .HasColumnType("float");

                    b.Property<string>("MaterialType")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("MeltingTemperature")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("PurchaseDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PurchaseLocation")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PurchaseNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PurchasePriceCurrency")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PurchasePriceValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double?>("RecommendedBedTemp")
                        .HasColumnType("float");

                    b.Property<double?>("RecommendedTemp")
                        .HasColumnType("float");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<long?>("SpoolWeightMg")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageLocation")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double?>("TempRangeEnd")
                        .HasColumnType("float");

                    b.Property<double?>("TempRangeStart")
                        .HasColumnType("float");

                    b.Property<long>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_Filaments_Id_Covering");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Id"), new[] { "DisplayName", "Brand", "MaterialType", "MaterialCategoryNickname", "MaterialDensityGramPerCubicCm", "ColorName", "ColorHex", "RecommendedTemp", "IsActive", "Notes", "CreatedDate", "PurchasePriceValue", "InitialNominalWeightMg", "DiameterMm", "StorageLocation", "IsFavorite", "InitialNominalVolumeMl" });

                    b.HasIndex("MaterialCategoryNickname");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Filaments");
                });

            modelBuilder.Entity("PrintLogApi.Models.FilamentAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("AmountMg")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FilamentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("LengthInM")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<long>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("VolumeMl")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FilamentId")
                        .HasDatabaseName("IX_FilamentAdjustments_FilamentId_Covering");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("FilamentId"), new[] { "AmountMg", "VolumeMl", "LengthInM", "CreatedDate", "Notes" });

                    b.HasIndex("UpdatedById");

                    b.ToTable("FilamentAdjustments");
                });

            modelBuilder.Entity("PrintLogApi.Models.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<long>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("PrintLogApi.Models.MaterialCategory", b =>
                {
                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("HasDiameter")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("ShowBedTemperature")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowInertGas")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowMaterialRefreshRatio")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowMeltingTemperature")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowNozzleTemperature")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowRecommendedInitialLayerTimeInSeconds")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowRecommendedLayerTimeInSeconds")
                        .HasColumnType("bit");

                    b.HasKey("Nickname");

                    b.ToTable("MaterialCategories");

                    b.HasData(
                        new
                        {
                            Nickname = "filament",
                            Description = "A single continuous filament of material",
                            HasDiameter = true,
                            Name = "Filament",
                            ShowBedTemperature = true,
                            ShowInertGas = false,
                            ShowMaterialRefreshRatio = false,
                            ShowMeltingTemperature = false,
                            ShowNozzleTemperature = true,
                            ShowRecommendedInitialLayerTimeInSeconds = false,
                            ShowRecommendedLayerTimeInSeconds = false
                        },
                        new
                        {
                            Nickname = "resin",
                            Description = "A photo-sensitive resin",
                            HasDiameter = false,
                            Name = "Resin",
                            ShowBedTemperature = false,
                            ShowInertGas = false,
                            ShowMaterialRefreshRatio = false,
                            ShowMeltingTemperature = false,
                            ShowNozzleTemperature = false,
                            ShowRecommendedInitialLayerTimeInSeconds = true,
                            ShowRecommendedLayerTimeInSeconds = true
                        },
                        new
                        {
                            Nickname = "powder",
                            Description = "A powder which is fused by heat or a binder",
                            HasDiameter = false,
                            Name = "Powder",
                            ShowBedTemperature = false,
                            ShowInertGas = true,
                            ShowMaterialRefreshRatio = true,
                            ShowMeltingTemperature = true,
                            ShowNozzleTemperature = false,
                            ShowRecommendedInitialLayerTimeInSeconds = false,
                            ShowRecommendedLayerTimeInSeconds = false
                        },
                        new
                        {
                            Nickname = "wire",
                            Description = "A continous wire",
                            HasDiameter = true,
                            Name = "Wire",
                            ShowBedTemperature = true,
                            ShowInertGas = false,
                            ShowMaterialRefreshRatio = false,
                            ShowMeltingTemperature = false,
                            ShowNozzleTemperature = true,
                            ShowRecommendedInitialLayerTimeInSeconds = false,
                            ShowRecommendedLayerTimeInSeconds = false
                        });
                });

            modelBuilder.Entity("PrintLogApi.Models.MaterialType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Acronym")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("DensityGramPerCubicCm")
                        .HasColumnType("float");

                    b.Property<string>("MaterialCategoryNickname")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialCategoryNickname");

                    b.ToTable("MaterialTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c78c56d0-b34d-49b1-849e-a54066a2f5e3"),
                            Acronym = "ABS",
                            DensityGramPerCubicCm = 1.1000000000000001,
                            MaterialCategoryNickname = "filament",
                            Name = "Acrylonitrile Butadiene Styrene"
                        },
                        new
                        {
                            Id = new Guid("c8cae1e0-5f13-41d6-9f72-cb83740aa2fe"),
                            Acronym = "CPE",
                            DensityGramPerCubicCm = 1.27,
                            MaterialCategoryNickname = "filament",
                            Name = "Co-polyester"
                        },
                        new
                        {
                            Id = new Guid("b0cda842-5a48-4a30-a060-226680e13c06"),
                            Acronym = "HIPS",
                            DensityGramPerCubicCm = 1.24,
                            MaterialCategoryNickname = "filament",
                            Name = "High Impact Polystyrene"
                        },
                        new
                        {
                            Id = new Guid("3dbc49c5-a493-4e21-a4d5-d94b8c0d53da"),
                            Acronym = "Nylon",
                            DensityGramPerCubicCm = 1.1399999999999999,
                            MaterialCategoryNickname = "filament"
                        },
                        new
                        {
                            Id = new Guid("7d83cbc1-00d0-4e42-a7ce-8a1b831b175b"),
                            Acronym = "PC",
                            DensityGramPerCubicCm = 1.1899999999999999,
                            MaterialCategoryNickname = "filament",
                            Name = "Polycarbonate"
                        },
                        new
                        {
                            Id = new Guid("35151bfe-6890-41ab-8fc9-443c5a690626"),
                            Acronym = "PCTG",
                            DensityGramPerCubicCm = 1.24,
                            MaterialCategoryNickname = "filament",
                            Name = "Cyclohexylenedimethylene Terephthalate Glycol"
                        },
                        new
                        {
                            Id = new Guid("23e38c0d-43f3-4bcd-b3c6-830d193a3e10"),
                            Acronym = "PETG",
                            DensityGramPerCubicCm = 1.3799999999999999,
                            MaterialCategoryNickname = "filament",
                            Name = "Polyethylene Terephthalate Glycol"
                        },
                        new
                        {
                            Id = new Guid("f8a6b364-94a6-4a32-a253-e67b41df1969"),
                            Acronym = "PLA",
                            DensityGramPerCubicCm = 1.24,
                            MaterialCategoryNickname = "filament",
                            Name = "Polylactic Acid"
                        },
                        new
                        {
                            Id = new Guid("0c236829-8487-4bb4-a092-68a9731a64e4"),
                            Acronym = "PVA",
                            DensityGramPerCubicCm = 1.23,
                            MaterialCategoryNickname = "filament",
                            Name = "Polyvinyl Acetate"
                        },
                        new
                        {
                            Id = new Guid("d777bde9-fba6-4f5a-b7a4-e8a4a9695715"),
                            Acronym = "TPU 95A",
                            DensityGramPerCubicCm = 1.22,
                            MaterialCategoryNickname = "filament",
                            Name = "Thermoplastic Polyurethane"
                        },
                        new
                        {
                            Id = new Guid("cc3a5fc9-39dd-42c6-8acc-9c9019dcd307"),
                            Acronym = "Standard Resin",
                            DensityGramPerCubicCm = 1.1000000000000001,
                            MaterialCategoryNickname = "resin",
                            Name = "Standard Resin"
                        });
                });

            modelBuilder.Entity("PrintLogApi.Models.McpIdempotencyRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CreatedPrintId")
                        .HasColumnType("bigint");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RequestFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ToolName", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_McpIdempotencyRecords_User_Tool_Key");

                    b.ToTable("McpIdempotencyRecords");
                });

            modelBuilder.Entity("PrintLogApi.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PrintId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ReadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("TriggeredByUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PrintId");

                    b.HasIndex("TriggeredByUserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Notifications_UserId_UnreadCount");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("UserId"), new[] { "IsRead" });

                    b.HasIndex("UserId", "IsRead", "CreatedDate")
                        .HasDatabaseName("IX_Notifications_UserId_IsRead_CreatedDate");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PrintLogApi.Models.Print", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AllowComments")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowFileDownloads")
                        .HasColumnType("bit");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EstimatedFilamentUsageMg")
                        .HasColumnType("int");

                    b.Property<int?>("EstimatedPrintTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<string>("FilamentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FilamentUsageMg")
                        .HasColumnType("int");

                    b.Property<byte[]>("FileHash")
                        .HasMaxLength(20)
                        .HasColumnType("varbinary(20)");

                    b.Property<string>("FileName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrintTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<long>("PrinterId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ViewStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_Prints_ProjectId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("CreatedById", "ViewStatus", "StartDate", "CreatedDate")
                        .HasDatabaseName("IX_Prints_Summary");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CreatedById", "ViewStatus", "StartDate", "CreatedDate"), new[] { "Id", "Title", "Status", "PrinterId", "EstimatedPrintTimeInSeconds", "PrintTimeInSeconds" });

                    b.ToTable("Prints");
                });

            modelBuilder.Entity("PrintLogApi.Models.PrintAttachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("PrintId")
                        .HasColumnType("bigint");

                    b.Property<long>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FileId");

                    b.HasIndex("PrintId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("PrintAttachments");
                });

            modelBuilder.Entity("PrintLogApi.Models.PrintComment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CommentId")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("PrintId")
                        .HasColumnType("bigint");

                    b.Property<long>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PrintId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("PrintComments");
                });

            modelBuilder.Entity("PrintLogApi.Models.PrintFilament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AmountMg")
                        .HasColumnType("int");

                    b.Property<int?>("EstimatedAmountMg")
                        .HasColumnType("int");

                    b.Property<double?>("EstimatedLengthInM")
                        .HasColumnType("float");

                    b.Property<int>("EstimatedSource")
                        .HasColumnType("int");

                    b.Property<double?>("EstimatedVolumeMl")
                        .HasColumnType("float");

                    b.Property<Guid?>("FilamentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("LengthInM")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("PrintId")
                        .HasColumnType("bigint");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<double?>("VolumeMl")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("FilamentId")
                        .HasDatabaseName("IX_PrintFilament_FilamentId_Covering");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("FilamentId"), new[] { "PrintId", "EstimatedAmountMg", "AmountMg", "EstimatedLengthInM", "LengthInM", "EstimatedVolumeMl", "VolumeMl", "EstimatedSource", "Source", "Notes" });

                    b.HasIndex("PrintId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PrintId"), new[] { "FilamentId", "AmountMg", "EstimatedAmountMg", "Notes", "EstimatedLengthInM", "LengthInM", "EstimatedSource", "EstimatedVolumeMl", "Source", "VolumeMl" });

                    b.ToTable("PrintFilament");
                });

            modelBuilder.Entity("PrintLogApi.Models.PrintImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<long>("PrintId")
                        .HasColumnType("bigint");

                    b.Property<long>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FileId");

                    b.HasIndex("PrintId")
                        .HasDatabaseName("IX_PrintImages_PrintId_Default")
                        .HasFilter("[IsDefault] = 1");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PrintId"), new[] { "Id", "FileId", "IsDefault", "CreatedDate", "CreatedById", "UpdatedDate", "UpdatedById" });

                    b.HasIndex("UpdatedById");

                    b.ToTable("PrintImages");
                });

            modelBuilder.Entity("PrintLogApi.Models.Printer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("BeamDiameter")
                        .HasColumnType("float");

                    b.Property<double?>("BedDepthMm")
                        .HasColumnType("float");

                    b.Property<double?>("BedHeightMm")
                        .HasColumnType("float");

                    b.Property<double?>("BedWidthMm")
                        .HasColumnType("float");

                    b.Property<string>("CategoryNickname")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("FFF");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double?>("FilamentDiameter")
                        .HasColumnType("float");

                    b.Property<bool?>("HasHeatedBed")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasHeatedChamber")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("NozzleDiameter")
                        .HasColumnType("float");

                    b.Property<double?>("ScreenResolutionXPixels")
                        .HasColumnType("float");

                    b.Property<double?>("ScreenResolutionYPixels")
                        .HasColumnType("float");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<double?>("WattageW")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryNickname");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_Printers_Id_Covering");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Id"), new[] { "UserId", "Make", "Model", "Description", "NozzleDiameter", "FilamentDiameter", "IsActive", "Name", "CategoryNickname", "BeamDiameter", "BedDepthMm", "BedHeightMm", "BedWidthMm", "HasHeatedBed", "HasHeatedChamber", "ScreenResolutionXPixels", "ScreenResolutionYPixels" });

                    b.HasIndex("UserId");

                    b.ToTable("Printers");
                });

            modelBuilder.Entity("PrintLogApi.Models.PrinterCategory", b =>
                {
                    b.Property<string>("Nickname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MaterialCategoryNickname")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ShowBeamDiameter")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowBedSize")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowFilamentDiameter")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowHasHeatedBed")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowHasHeatedChamber")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowNozzleDiameter")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowScreenResolution")
                        .HasColumnType("bit");

                    b.HasKey("Nickname");

                    b.HasIndex("MaterialCategoryNickname");

                    b.ToTable("PrinterCategories");

                    b.HasData(
                        new
                        {
                            Nickname = "FDM",
                            Description = "Material extruded through a nozzle.",
                            MaterialCategoryNickname = "filament",
                            Name = "Fused Deposition Modeling",
                            ShowBeamDiameter = false,
                            ShowBedSize = true,
                            ShowFilamentDiameter = true,
                            ShowHasHeatedBed = true,
                            ShowHasHeatedChamber = true,
                            ShowNozzleDiameter = true,
                            ShowScreenResolution = false
                        },
                        new
                        {
                            Nickname = "FFF",
                            Description = "Material extruded through a nozzle.",
                            MaterialCategoryNickname = "filament",
                            Name = "Fused Filament Fabrication",
                            ShowBeamDiameter = false,
                            ShowBedSize = true,
                            ShowFilamentDiameter = true,
                            ShowHasHeatedBed = true,
                            ShowHasHeatedChamber = true,
                            ShowNozzleDiameter = true,
                            ShowScreenResolution = false
                        },
                        new
                        {
                            Nickname = "SLA",
                            Description = "Laser based SLA which cures photosensitive resin.",
                            MaterialCategoryNickname = "resin",
                            Name = "Stereolithography",
                            ShowBeamDiameter = true,
                            ShowBedSize = true,
                            ShowFilamentDiameter = false,
                            ShowHasHeatedBed = false,
                            ShowHasHeatedChamber = true,
                            ShowNozzleDiameter = false,
                            ShowScreenResolution = false
                        },
                        new
                        {
                            Nickname = "PolyJet",
                            Description = "Printing with UV curable resin onto a build tray in a process somewhat similar to inkjet printing.",
                            MaterialCategoryNickname = "resin",
                            Name = "PolyJet",
                            ShowBeamDiameter = false,
                            ShowBedSize = true,
                            ShowFilamentDiameter = false,
                            ShowHasHeatedBed = false,
                            ShowHasHeatedChamber = true,
                            ShowNozzleDiameter = false,
                            ShowScreenResolution = true
                        },
                        new
                        {
                            Nickname = "LCD",
                            Description = "Uses an LCD Screen to mask photosensitive resin.",
                            MaterialCategoryNickname = "resin",
                            Name = "Liquid Crystal Display",
                            ShowBeamDiameter = false,
                            ShowBedSize = true,
                            ShowFilamentDiameter = false,
                            ShowHasHeatedBed = false,
                            ShowHasHeatedChamber = true,
                            ShowNozzleDiameter = false,
                            ShowScreenResolution = true
                        },
                        new
                        {
                            Nickname = "DLP",
                            Description = "Uses a projector or projector-like array to expose a photosensitive resin.",
                            MaterialCategoryNickname = "resin",
                            Name = "Digital Light Processing",
                            ShowBeamDiameter = false,
                            ShowBedSize = true,
                            ShowFilamentDiameter = false,
                            ShowHasHeatedBed = false,
                            ShowHasHeatedChamber = true,
                            ShowNozzleDiameter = false,
                            ShowScreenResolution = true
                        },
                        new
                        {
                            Nickname = "MSLA",
                            Description = "Uses an LED array along with a LCD Photomask to selectively expose a photosensitive resin.",
                            MaterialCategoryNickname = "resin",
                            Name = "Micro-stereolithography",
                            ShowBeamDiameter = false,
                            ShowBedSize = true,
                            ShowFilamentDiameter = false,
                            ShowHasHeatedBed = false,
                            ShowHasHeatedChamber = true,
                            ShowNozzleDiameter = false,
                            ShowScreenResolution = true
                        },
                        new
                        {
                            Nickname = "SLS",
                            Description = "Uses a laser to fuse particles together.",
                            MaterialCategoryNickname = "powder",
                            Name = "Selective Laser Sintering",
                            ShowBeamDiameter = true,
                            ShowBedSize = true,
                            ShowFilamentDiameter = false,
                            ShowHasHeatedBed = false,
                            ShowHasHeatedChamber = true,
                            ShowNozzleDiameter = false,
                            ShowScreenResolution = false
                        },
                        new
                        {
                            Nickname = "LPDF",
                            Description = "Generic category for powder based additive manufacturing.",
                            MaterialCategoryNickname = "powder",
                            Name = "Laser Powder Bed Fusion",
                            ShowBeamDiameter = true,
                            ShowBedSize = true,
                            ShowFilamentDiameter = false,
                            ShowHasHeatedBed = false,
                            ShowHasHeatedChamber = true,
                            ShowNozzleDiameter = false,
                            ShowScreenResolution = false
                        },
                        new
                        {
                            Nickname = "EBM",
                            Description = "Uses an electron beam to fuse particles together.",
                            MaterialCategoryNickname = "powder",
                            Name = "Electron Beam Melting",
                            ShowBeamDiameter = true,
                            ShowBedSize = true,
                            ShowFilamentDiameter = false,
                            ShowHasHeatedBed = false,
                            ShowHasHeatedChamber = true,
                            ShowNozzleDiameter = false,
                            ShowScreenResolution = false
                        });
                });

            modelBuilder.Entity("PrintLogApi.Models.PrinterFilament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FilamentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LoadedDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("PrinterId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UnloadedDateTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FilamentId")
                        .HasFilter("[UnloadedDateTime] IS NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("FilamentId"), new[] { "PrinterId", "UnloadedDateTime" });

                    b.HasIndex("PrinterId")
                        .HasFilter("[UnloadedDateTime] IS NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PrinterId"), new[] { "FilamentId", "UnloadedDateTime" });

                    b.ToTable("PrinterFilament");
                });

            modelBuilder.Entity("PrintLogApi.Models.PrinterMaintenance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Done")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PriceValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("PrinterId")
                        .HasColumnType("bigint");

                    b.Property<long>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CreatedById"), new[] { "Date", "CreatedDate" });

                    b.HasIndex("PrinterId");

                    b.HasIndex("UpdatedById");

                    b.ToTable("PrinterMaintenance");
                });

            modelBuilder.Entity("PrintLogApi.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ViewStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("CreatedById", "CreatedDate")
                        .HasDatabaseName("IX_Projects_CreatedById_CreatedDate");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CreatedById", "CreatedDate"), new[] { "Id", "Name", "Status", "ViewStatus", "Reference" });

                    b.HasIndex("CreatedById", "UpdatedDate")
                        .HasDatabaseName("IX_Projects_CreatedById_UpdatedDate");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CreatedById", "UpdatedDate"), new[] { "Id", "Name", "Status", "ViewStatus", "Reference" });

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("PrintLogApi.Models.ProjectImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FileId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_ProjectImages_ProjectId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ProjectId"), new[] { "Id", "FileId", "IsDefault", "DisplayOrder", "CreatedDate", "CreatedById" });

                    b.HasIndex("UpdatedById");

                    b.ToTable("ProjectImages");
                });

            modelBuilder.Entity("PrintLogApi.Models.Subscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("CancelAtPeriodEnd")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("CanceledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("CurrentPeriodStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Plan")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("StripeCustomerId")
                        .HasDatabaseName("IX_Subscriptions_StripeCustomerId");

                    b.HasIndex("StripeSubscriptionId")
                        .HasDatabaseName("IX_Subscriptions_StripeSubscriptionId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Subscriptions_UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("PrintLogApi.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CoverPicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeactivationDateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OAuthUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ViewStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OAuthUserId")
                        .IsUnique()
                        .HasFilter("[OAuthUserId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PrintLogApi.Models.UserApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("HashedKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastUsed")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.ToTable("UserApiKeys");
                });

            modelBuilder.Entity("PrintLogApi.Models.UserSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("UpdatedById")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserSettingTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSettingTypeId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("PrintLogApi.Models.UserSettingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UserSettingTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The Default View Status for a print.",
                            Name = "Prints_DefaultPrintViewStatus"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The Id of the printer that was last selected.",
                            Name = "Prints_LastSelectedPrinterId"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The value of the last changed Allow Comments on prints.",
                            Name = "Prints_LastSelectedAllowComments"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The last selected filament measure type on the print.",
                            Name = "Prints_LastSelectedFilamentMeasureType"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The three-character country code of the preferred currency",
                            Name = "Currency_Name"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The symbol of the preferred currency",
                            Name = "Currency_Symbol"
                        },
                        new
                        {
                            Id = 7,
                            Description = "The default diameter of new filament (in millimeters).",
                            Name = "Filaments_DefaultDiameterMm"
                        },
                        new
                        {
                            Id = 8,
                            Description = "The default price of filament, for when pricing wasn't added.",
                            Name = "Filaments_DefaultPrice"
                        },
                        new
                        {
                            Id = 9,
                            Description = "The last selected resin measure type on the print.",
                            Name = "Prints_LastSelectedResinMeasureType"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The last selected powder measure type on the print.",
                            Name = "Prints_LastSelectedPowderMeasureType"
                        },
                        new
                        {
                            Id = 11,
                            Description = "The last selected wire measure type on the print.",
                            Name = "Prints_LastSelectedWireMeasureType"
                        },
                        new
                        {
                            Id = 14,
                            Description = "The user's preferred unit for displaying filament usage (1=Weight, 2=Length, 3=Volume).",
                            Name = "Prints_PreferredFilamentDisplayUnit"
                        });
                });

            modelBuilder.Entity("PrintLogApi.Models.Comment", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrintLogApi.Models.Feedback", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrintLogApi.Models.Filament", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.MaterialCategory", "MaterialCategory")
                        .WithMany()
                        .HasForeignKey("MaterialCategoryNickname")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("MaterialCategory");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrintLogApi.Models.FilamentAdjustment", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.Filament", "Filament")
                        .WithMany("FilamentAdjustments")
                        .HasForeignKey("FilamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Filament");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrintLogApi.Models.File", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrintLogApi.Models.MaterialType", b =>
                {
                    b.HasOne("PrintLogApi.Models.MaterialCategory", "MaterialCategory")
                        .WithMany()
                        .HasForeignKey("MaterialCategoryNickname");

                    b.Navigation("MaterialCategory");
                });

            modelBuilder.Entity("PrintLogApi.Models.Notification", b =>
                {
                    b.HasOne("PrintLogApi.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId");

                    b.HasOne("PrintLogApi.Models.Print", "Print")
                        .WithMany()
                        .HasForeignKey("PrintId");

                    b.HasOne("PrintLogApi.Models.User", "TriggeredByUser")
                        .WithMany()
                        .HasForeignKey("TriggeredByUserId");

                    b.HasOne("PrintLogApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Print");

                    b.Navigation("TriggeredByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrintLogApi.Models.Print", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.Printer", "Printer")
                        .WithMany()
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.Project", "Project")
                        .WithMany("Prints")
                        .HasForeignKey("ProjectId");

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Printer");

                    b.Navigation("Project");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrintLogApi.Models.PrintAttachment", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.Print", "Print")
                        .WithMany("Attachments")
                        .HasForeignKey("PrintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("File");

                    b.Navigation("Print");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrintLogApi.Models.PrintComment", b =>
                {
                    b.HasOne("PrintLogApi.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.Print", "Print")
                        .WithMany("Comments")
                        .HasForeignKey("PrintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("CreatedBy");

                    b.Navigation("Print");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrintLogApi.Models.PrintFilament", b =>
                {
                    b.HasOne("PrintLogApi.Models.Filament", "Filament")
                        .WithMany("PrintFilaments")
                        .HasForeignKey("FilamentId");

                    b.HasOne("PrintLogApi.Models.Print", "Print")
                        .WithMany("FilamentUsage")
                        .HasForeignKey("PrintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filament");

                    b.Navigation("Print");
                });

            modelBuilder.Entity("PrintLogApi.Models.PrintImage", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.Print", "Print")
                        .WithMany("Images")
                        .HasForeignKey("PrintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("File");

                    b.Navigation("Print");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrintLogApi.Models.Printer", b =>
                {
                    b.HasOne("PrintLogApi.Models.PrinterCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryNickname");

                    b.HasOne("PrintLogApi.Models.User", "User")
                        .WithMany("printers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrintLogApi.Models.PrinterCategory", b =>
                {
                    b.HasOne("PrintLogApi.Models.MaterialCategory", "MaterialCategory")
                        .WithMany()
                        .HasForeignKey("MaterialCategoryNickname");

                    b.Navigation("MaterialCategory");
                });

            modelBuilder.Entity("PrintLogApi.Models.PrinterFilament", b =>
                {
                    b.HasOne("PrintLogApi.Models.Filament", "Filament")
                        .WithMany("PrinterFilaments")
                        .HasForeignKey("FilamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.Printer", "Printer")
                        .WithMany("LoadedFilaments")
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filament");

                    b.Navigation("Printer");
                });

            modelBuilder.Entity("PrintLogApi.Models.PrinterMaintenance", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.Printer", "Printer")
                        .WithMany()
                        .HasForeignKey("PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Printer");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrintLogApi.Models.Project", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrintLogApi.Models.ProjectImage", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.File", "File")
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.Project", "Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("File");

                    b.Navigation("Project");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("PrintLogApi.Models.Subscription", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrintLogApi.Models.UserApiKey", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrintLogApi.Models.UserSetting", b =>
                {
                    b.HasOne("PrintLogApi.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrintLogApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.HasOne("PrintLogApi.Models.UserSettingType", "UserSettingType")
                        .WithMany()
                        .HasForeignKey("UserSettingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");

                    b.Navigation("UserSettingType");
                });

            modelBuilder.Entity("PrintLogApi.Models.Filament", b =>
                {
                    b.Navigation("FilamentAdjustments");

                    b.Navigation("PrintFilaments");

                    b.Navigation("PrinterFilaments");
                });

            modelBuilder.Entity("PrintLogApi.Models.Print", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("FilamentUsage");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("PrintLogApi.Models.Printer", b =>
                {
                    b.Navigation("LoadedFilaments");
                });

            modelBuilder.Entity("PrintLogApi.Models.Project", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Prints");
                });

            modelBuilder.Entity("PrintLogApi.Models.User", b =>
                {
                    b.Navigation("printers");
                });
#pragma warning restore 612, 618
        }
    }
}
